### ISSUE TITLE
Inaccurate case in inference for new character

### ISSUE THREAD

**Issue by WinKawaks** [xiyichen/morphablediffusion#3]
When I tried to change the source image to a new character, I got this result.

![out](https://github.com/xiyichen/morphablediffusion/assets/20330575/3f1bbec7-d883-40a2-9eb0-b70ab897e44b)

Is there a way to improve the quality with inference only? Or is it necessary to finetune the model?

**Comment by xiyichen** [comment]
Our model doesn't always generalize well to unseen subjects. Currently, the only way to encode the identity of the input subject is from CLIP embeddings. It works OK for general objects but isn't so reliable for human faces. We are still exploring more efficient ways to maintain the resemblance. A more important reason is that our training data only covers Asian subjects wearing red swimming caps, which means the hairstyles are not learned by the model. We are interested in trying our method on the [RenderMe360 dataset](https://renderme-360.github.io/inner-download.html#Download), but I'm not sure when they will release the whole dataset with all subjects.

**Comment by AvirupJU** [comment]
I think it's still an open problem. ID consistency with these models is a tricky thing. Even models like diffusion rig, headnerf fail when the test image is out of distribution though they are trained on diverse datasets.
