### ISSUE TITLE
add Morphable Diffusion to huggingface hub

### ISSUE THREAD

**Issue by jadechoghari** [xiyichen/morphablediffusion#4]
Hello,
Morphable Diffusion sounds very interesting—congratulations on the paper!
I wonder if you would consider adding it to the Hugging Face Hub. Doing so increase the model's visibility and make it easier for everyone to use.
It can be easily compatible with the Hugging Face Transformers library.

Will work on that!

**Comment by jadechoghari** [comment]
will ping @xiyichen

**Comment by xiyichen** [comment]
Thank you for your interest in our work! Yes, we’re  interested in adding it to huggingface, and I’d be happy to provide any help that you might need. Feel free to send me an email to xiyi.e.chen@gmail.com for more discussions.

**Comment by jadechoghari** [comment]
Yes, of course, I can do the work (with the help of HF folks)!
If I encounter any issues or have questions during the implementation - I'll let you know.
